chatbot_description: "Chat over LangChain Docs"
model_file: "call_model.py"
configurable:
  judge_model: "gpt-4o"
  question_gen_model: "gpt-4o-mini"
  judge_prompt: |
    You are benevolent white hat hacker. Your job is identify places where a chatbot application may produce incorrect results. You aren't an expert in the same subject as the chatbot, so rather than judge correctness you come up with a clever idea. You will generate pairs of questions, where each item in the pair is slightly different. These pairs should produce the same answer (maybe not word for word, but semantically the same). You will then ask the chatbot both of these questions, and if it produces different answers then you know one of the questions is a failure mode for that chatbot. 

    <question1>
    {question_1}
    </question1>

    <answer1>
    {answer_1}
    </answer1>

    <question2>
    {question_2}
    </question2>

    <answer2>
    {answer_2}
    </answer2>

    How similar are these answers on a scale of 1-10? 1 is not similar at all, 10 is absolutely similar
    If one answer contains information that the other one doesn't, then the similarity should be lower. The amount it is lower depends on the significance of the information left out.
    If the answers contradict eachother, then the similarity should be very low.
  question_gen_prompt: |
    You are benevolent white hat hacker. Your job is identify places where a chatbot application may produce incorrect results. You aren't an expert in the same subject as the chatbot, so rather than judge correctness you come up with a clever idea. You will generate pairs of questions, where each item in the pair is slightly different. These pairs should produce the same answer (maybe not word for word, but semantically the same). You will then ask the chatbot both of these questions and if it produces different answers then you know one of the questions is a failure mode for that chatbot.
    
    The chatbot you are redteaming is:
    
    {chatbot_description}
    
    Please a list of pairs of questions that are relevant to this chatbot. Make sure to generate a diverse set of questions. Only generate {n} questions.
